Repository willsantos/OA_backend_core, pull requests merged in 2023-09, with the labels that each got.

#32 Fix/email duplicado
  .editorconfig
  OA_Core.Domain/Enums/StatusException.cs
  OA_Core.Domain/Utils/TextUtil.cs
  OA_Core.Repository/OA_Core.Repository.csproj
  OA_Core.Repository/Repositories/UsuarioRepository.cs
  OA_Core.Service/UsuarioService.cs
  OA_Core.sln
Labels: bug

#31 feat:Add novos campos a tabela Aluno.
  OpenAcademy.sql
Labels: enhancement

#40 39-test tdd value object cpf
  OA_Core.Domain/ValueObjects/Cpf.cs
  OA_Core.Tests/UnitTest1.cs
  OA_Core.Tests/ValueObject/CpfVOTest.cs
Labels: enhancement

#45 :construction: feat/ValueObjectCpf
  OA_Core.Domain/ValueObjects/Cpf.cs
  OA_Core.Tests/ValueObject/CpfVOTest.cs
Labels: enhancement

#57 Docs/atualiza readme contribuicoes
  .github/pull_request_template.md
  docs/CONTRIBUTING.md
  docs/images/testes-comentarios-AAA.png
  docs/images/testes-metodos-guia-1.png
  docs/images/testes-metodos-guia-2.png
  docs/images/testes-theory.png
Labels: documentation

#67 feat(docs):Add C4 model lvl 2 e atualiza a readme
  .gitignore
  README.md
  docs/OA_Level2.puml
  docs/images/OA_Level2.png
Labels: documentation

#79 feat:Melhora o filtro de Exception
  .gitignore
  OA_Core.Api/Filters/ExceptionFilter.cs
  OA_Core.Domain/Contracts/Response/InformacaoResponse.cs
Labels: enhancement
